// Generated by training/convert.py. Do not edit.
#pragma once

extern const unsigned char g_model_data[];
extern const unsigned int g_model_data_len;

// Input features, from training/preprocess.py: x[i] = clip(ln(v[i] / mean(v[0..REF-1])), LO, HI)
#define MODEL_WINDOW 100
#define MODEL_REF_SAMPLES 10
#define MODEL_CLIP_LO -1.0f
#define MODEL_CLIP_HI 4.0f

#define MODEL_CLASS_COUNT 4
static const char *const kModelClasses[MODEL_CLASS_COUNT] = { "clean", "breath", "alcohol", "smoke" };
