#!/usr/bin/env python3
"""Quantise the trained model to 8-bit integers and export it as C source (tutorial stage 7).

    convert.py      # writes training/model/model.tflite and firmware/inference/main/model_data.{h,cc}
"""
import os
from pathlib import Path

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

import numpy as np
import tensorflow as tf

from preprocess import CLIP_HI, CLIP_LO, REF, WINDOW

ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = ROOT / "data" / "processed" / "windows.npz"
MODEL_FILE = ROOT / "training" / "model" / "model.keras"
TFLITE_FILE = ROOT / "training" / "model" / "model.tflite"
C_DIR = ROOT / "firmware" / "inference" / "main"


def quantise(model, X):
    def representative():
        # Real inputs, so the converter can measure the range of values each layer produces.
        for i in np.random.default_rng(0).permutation(len(X))[:300]:
            yield [X[i:i + 1]]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative
    # Integers everywhere, including the input and output, so the board needs no float kernels.
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()


def run_int8(tflite, X):
    # Reference kernels round exactly as TensorFlow Lite Micro does, so these results are the board's results.
    interpreter = tf.lite.Interpreter(model_content=tflite,
                                      experimental_op_resolver_type=tf.lite.experimental.OpResolverType.BUILTIN_REF)
    interpreter.allocate_tensors()
    inp, out = interpreter.get_input_details()[0], interpreter.get_output_details()[0]
    scale, zero = inp["quantization"]
    predictions = []
    for x in X:
        q = np.clip(np.round(x / scale) + zero, -128, 127).astype(np.int8)
        interpreter.set_tensor(inp["index"], q[None])
        interpreter.invoke()
        predictions.append(interpreter.get_tensor(out["index"])[0].argmax())
    # DELEGATE is the PC interpreter's own accelerator, not an operator stored in the model.
    ops = sorted({op["op_name"] for op in interpreter._get_ops_details()} - {"DELEGATE"})
    return np.array(predictions), inp, out, ops


def write_c(tflite, classes):
    C_DIR.mkdir(parents=True, exist_ok=True)
    rows = [", ".join(f"0x{b:02x}" for b in tflite[i:i + 12]) for i in range(0, len(tflite), 12)]
    (C_DIR / "model_data.cc").write_text(
        "// Generated by training/convert.py. Do not edit.\n"
        '#include "model_data.h"\n\n'
        "alignas(16) const unsigned char g_model_data[] = {\n    " + ",\n    ".join(rows) + ",\n};\n"
        f"const unsigned int g_model_data_len = {len(tflite)};\n")
    names = ", ".join(f'"{c}"' for c in classes)
    (C_DIR / "model_data.h").write_text(
        "// Generated by training/convert.py. Do not edit.\n"
        "#pragma once\n\n"
        "extern const unsigned char g_model_data[];\n"
        "extern const unsigned int g_model_data_len;\n\n"
        "// Input features, from training/preprocess.py: x[i] = clip(ln(v[i] / mean(v[0..REF-1])), LO, HI)\n"
        f"#define MODEL_WINDOW {WINDOW}\n"
        f"#define MODEL_REF_SAMPLES {REF}\n"
        f"#define MODEL_CLIP_LO {CLIP_LO}f\n"
        f"#define MODEL_CLIP_HI {CLIP_HI}f\n\n"
        f"#define MODEL_CLASS_COUNT {len(classes)}\n"
        f"static const char *const kModelClasses[MODEL_CLASS_COUNT] = {{ {names} }};\n")


def main():
    data = np.load(DATA_FILE)
    X = data["X"][..., None].astype(np.float32)
    classes = [str(c) for c in data["classes"]]
    model = tf.keras.models.load_model(MODEL_FILE)

    tflite = quantise(model, X)
    TFLITE_FILE.write_bytes(tflite)
    write_c(tflite, classes)

    float_pred = model.predict(X, verbose=0).argmax(1)
    int8_pred, inp, out, ops = run_int8(tflite, X)
    print(f"model.tflite: {len(tflite)} bytes")
    print(f"input  int8, scale {inp['quantization'][0]:.6f}, zero point {inp['quantization'][1]}")
    print(f"output int8, scale {out['quantization'][0]:.6f}, zero point {out['quantization'][1]}")
    print(f"operators: {', '.join(ops)}")
    print(f"float and int8 models agree on {np.mean(float_pred == int8_pred):.1%} of {len(X)} windows")
    print(f"accuracy on the training windows: float {np.mean(float_pred == data['y']):.1%}, "
          f"int8 {np.mean(int8_pred == data['y']):.1%}")


if __name__ == "__main__":
    main()
